version: "3.4"

services:
  app:
    build: ./app
    depends_on:
      - db
    env_file: .env
    volumes:
      - data:/var/www/html/storage
      - www:/var/www/html
    restart: always

  web:
    build: ./web
    restart: always
    ports:
      - 80:80
    volumes:
      - data:/var/www/html/storage:ro
      - www:/var/www/html:ro
    depends_on:
      - app

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
  www:
  mysql:
