# Run Monica with nginx proxy and specific file size limits
#
# You might want to set these variables in you .env file:
#
#- APP_ENV=production
#- APP_URL with your domain (https scheme)
#- APP_KEY with a random string
#
#- DB_HOST=db
# See `db` container for these values:
#- DB_DATABASE=monica
#- DB_USERNAME=monica
#- DB_PASSWORD=secret
#
# Also set this to the appropriate limit:
#- DEFAULT_MAX_UPLOAD_SIZE=500000
#

version: "3.9"

services:
  app:
    build: ./app
    image: monica-app
    env_file: .env
    depends_on:
      - db
    volumes:
      - data:/var/www/html/storage
    restart: always

  web:
    build: ./web
    image: monica-web
    restart: always
    ports:
      - 80:80
    volumes:
      - data:/var/www/html/storage:ro
    depends_on:
      - app

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always


volumes:
  data:
    driver: local
  mysqldata:
    driver: local
